# Generated by Django 4.2.17 on 2026-07-01 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='out_files/')),
                ('system_name', models.CharField(blank=True, default='', max_length=255)),
                ('atom_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='out_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visualizer_outfile',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
