# Generated by Django 4.2.1 on 2026-02-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('system_name', models.CharField(max_length=255)),
                ('fdf_content', models.TextField()),
                ('parameters', models.JSONField()),
                ('conversion_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField()),
                ('download_count', models.IntegerField()),
            ],
            options={
                'db_table': 'converter_conversionhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parameters', models.JSONField()),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('last_used', models.DateTimeField()),
                ('use_count', models.IntegerField()),
            ],
            options={
                'db_table': 'converter_savedconfiguration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField()),
                ('is_temp', models.BooleanField()),
            ],
            options={
                'db_table': 'converter_uploadedfile',
                'managed': False,
            },
        ),
    ]
