# Generated by Django 4.2.17 on 2026-03-07 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField()),
                ('is_temp', models.BooleanField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'converter_uploadedfile',
            },
        ),
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('system_name', models.CharField(max_length=255)),
                ('fdf_content', models.TextField()),
                ('parameters', models.JSONField()),
                ('conversion_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField()),
                ('download_count', models.IntegerField()),
                ('uploaded_file', models.ForeignKey(blank=True, db_column='uploaded_file_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.uploadedfile')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'converter_conversionhistory',
            },
        ),
        migrations.CreateModel(
            name='SavedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parameters', models.JSONField()),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('last_used', models.DateTimeField()),
                ('use_count', models.IntegerField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'converter_savedconfiguration',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
