# Generated by Django 4.2.17 on 2026-09-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_conversionhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pseudopotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=3)),
                ('functional', models.CharField(default='lda', max_length=10)),
                ('file', models.FileField(upload_to='pseudos/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'converter_pseudopotential',
                'ordering': ['symbol', 'functional'],
                'unique_together': {('symbol', 'functional')},
            },
        ),
    ]
