"""
Django settings for heparin_converter project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente.
# 1) No Render, Secret Files são montados em /etc/secrets/ e o find_dotenv() do
#    python-dotenv não olha para lá: ele sobe a árvore a partir deste arquivo,
#    procurando apenas BASE_DIR/.env. Sem esta chamada explícita, um .env
#    enviado como Secret File é silenciosamente ignorado.
# 2) Em seguida, o .env do projeto (desenvolvimento local).
# Nenhuma das chamadas sobrescreve variáveis já presentes no ambiente do
# processo — logo, o painel do Render sempre tem precedência.
_RENDER_SECRET_ENV = Path('/etc/secrets/.env')
if _RENDER_SECRET_ENV.is_file():
    load_dotenv(_RENDER_SECRET_ENV)
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if DEBUG and not SECRET_KEY:
    SECRET_KEY = 'django-insecure-fallback-key-for-development'
# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '[::1]']
elif not ALLOWED_HOSTS:
    # Em produção, configure ALLOWED_HOSTS no ambiente. Fallback para o Render.
    ALLOWED_HOSTS = ['.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'converter',
    'user',
    'dashboard',
    'visualizer',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'heparin_converter.middleware.DefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heparin_converter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'heparin_converter.wsgi.application'

# Configurações de mídia para uploads de arquivos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
PSEUDOPOTENTIALS_DIR = os.path.join(BASE_DIR, 'pseudos')
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

def _postgres_from_url(url):
    """Monta a config de DATABASES a partir de uma DATABASE_URL.

    Formato usado por Render Postgres, Supabase, Heroku, etc.
    (ex: postgres://user:senha@host:5432/banco?sslmode=require).
    Usa apenas a biblioteca padrão para não adicionar dj-database-url.
    """
    parsed = urlparse(url)
    if parsed.scheme not in ('postgres', 'postgresql', 'pgsql'):
        raise ImproperlyConfigured(
            f"DATABASE_URL com esquema não suportado: '{parsed.scheme}'. "
            "Use postgres:// ou postgresql://."
        )

    try:
        port = parsed.port or 5432
    except ValueError:
        raise ImproperlyConfigured("DATABASE_URL contém uma porta inválida.")

    query = parse_qs(parsed.query)
    sslmode = (query.get('sslmode') or [os.environ.get('DB_SSLMODE', 'require')])[0]

    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(parsed.path.lstrip('/')),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(port),
        'OPTIONS': {'sslmode': sslmode},
    }


def _postgres_from_pg_env():
    """Config de banco a partir das variáveis PGHOST/PGDATABASE/... do Render."""
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('PGDATABASE'),
        'USER': os.environ.get('PGUSER'),
        'PASSWORD': os.environ.get('PGPASSWORD'),
        'HOST': os.environ.get('PGHOST'),
        'PORT': os.environ.get('PGPORT', '5432'),
        'OPTIONS': {'sslmode': os.environ.get('DB_SSLMODE', 'require')},
    }


def _production_database():
    """Resolve a config de banco de produção (DEBUG=False).

    Ordem de precedência:
      1. DB_ENGINE + DB_NAME/DB_USER/DB_PASSWORD/DB_HOST/DB_PORT (explícito)
      2. DATABASE_URL (Render Postgres, Supabase, Heroku...)
      3. PGHOST/PGDATABASE/PGUSER/PGPASSWORD (Postgres vinculado no Render)

    Retorna {} quando nada está definido. Nesse caso o Django usa o backend
    'dummy' e qualquer conexão falha — por isso o entrypoint.sh valida a
    configuração antes de tentar conectar e aborta com uma mensagem explícita.
    """
    if os.environ.get('DB_ENGINE'):
        return {
            'ENGINE': os.environ['DB_ENGINE'],
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT'),
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', default='require'),
                # Você pode precisar de outras opções SSL dependendo da configuração do servidor,
                # como 'sslrootcert', 'sslcert', 'sslkey', mas 'require' é um bom começo
                # para bancos de dados hospedados que fornecem SSL automaticamente.
            }
        }

    if os.environ.get('DATABASE_URL'):
        return _postgres_from_url(os.environ['DATABASE_URL'])

    if os.environ.get('PGHOST'):
        return _postgres_from_pg_env()

    return {}


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {'default': _production_database()}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# WhiteNoise para servir estáticos comprimidos (Brotli/Gzip)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# API REST
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Celery (processamento assíncrono)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Em DEBUG/testes as tarefas rodam de forma síncrona (sem broker)
CELERY_TASK_ALWAYS_EAGER = (
    os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'True' if DEBUG else 'False').lower() == 'true'
)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BEAT_SCHEDULE = {
    'cleanup-temp-files-daily': {
        'task': 'converter.cleanup_temp_files',
        'schedule': 60 * 60 * 24,
        'args': (30,),
    },
}

# Tempo de validade do link de redefinição de senha (24h — coerente com o e-mail)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# Email backend: print to console in dev, use SMTP in production
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# E-mail que recebe as mensagens do formulário de contato
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'gusgurtavo@gmail.com')

# Hardening de produção
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 365))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True